

export INSTALL_DIR=$HOME/test_install_ccs
export BUILD_DIR=$HOME/test_build_ccs


export PATH=$PATH:$INSTALL_DIR/makedepf90/bin

export PYTHONPATH=$PYTHONPATH:$INSTALL_DIR/python-$CMP
export PATH=$PATH:$INSTALL_DIR/python-$CMP/bin
export PYTHONUSERBASE=$INSTALL_DIR/python-$CMP

export PETSC=$INSTALL_DIR/petsc-$CMP
export LD_LIBRARY_PATH=$PETSC/lib:$LD_LIBRARY_PATH

export FYAML=$INSTALL_DIR/fyaml-$CMP
export FYAMLC=$INSTALL_DIR/fyaml-c-$CMP
  
export ADIOS2=$INSTALL_DIR/adios2-$CMP
export HDF5_ROOT=$INSTALL_DIR/hdf5-$CMP

export PARHIP=$INSTALL_DIR/parhip-$CMP
export LD_LIBRARY_PATH=$PARHIP/lib:$LD_LIBRARY_PATH
  
export PARMETIS=$INSTALL_DIR/parmetis-$CMP
export LD_LIBRARY_PATH=$PARMETIS/lib:$LD_LIBRARY_PATH

export RCMF90=$INSTALL_DIR/rcm-f90-$CMP
export LD_LIBRARY_PATH=$RCMF90/lib:$LD_LIBRARY_PATH

export MAKEDEPF90=$INSTALL_DIR/makedepf90-$CMP
export PATH=$PATH:$MAKEDEPf90/bin
