#!/bin/bash

export INSTALL_DIR=
export BUILD_DIR=/tmp/build-ccs-deps/

export ADIOS2_VERSION=2.12.1
export PARHIP_VERSION=3.25
export PETSC_VERSION=3.25.4
export HDF5_VERSION=2.2.0
export FYAMLC_VERSION=0.2.6
export CALIPER_VERSION=2.15.0
export LIKWID_VERSION=5.5.2

export PYTHONPATH=$PYTHONPATH:$INSTALL_DIR/python-$CMP
export PATH=$PATH:$INSTALL_DIR/python-$CMP/bin
export PYTHONUSERBASE=$INSTALL_DIR/python-$CMP

export PETSC=$INSTALL_DIR/petsc-$CMP-v$PETSC_VERSION
export PETSC_ROOT=$PETSC
export PETSC_DIR=$PETSC
export LD_LIBRARY_PATH=${PETSC}/lib:$LD_LIBRARY_PATH

export FYAMLC=$INSTALL_DIR/fyaml-c-$CMP-v$FYAMLC_VERSION
export LD_LIBRARY_PATH=$FYAMLC/lib:$LD_LIBRARY_PATH
  
export ADIOS2=$INSTALL_DIR/adios2-$CMP-v$ADIOS2_VERSION
export HDF5_ROOT=$INSTALL_DIR/hdf5-$CMP-v$HDF5_VERSION

export PARHIP=$INSTALL_DIR/parhip-$CMP-v$PARHIP_VERSION
export LD_LIBRARY_PATH=$PARHIP/lib:$LD_LIBRARY_PATH
  
export PARMETIS=$INSTALL_DIR/parmetis-$CMP
export LD_LIBRARY_PATH=$PARMETIS/lib:$LD_LIBRARY_PATH

export PARMETIS_32bit=$INSTALL_DIR/parmetis-$CMP-32bit
export LD_LIBRARY_PATH=$PARMETIS_32bit/lib:$LD_LIBRARY_PATH

export RCMF90=$INSTALL_DIR/rcm-f90-$CMP
export LD_LIBRARY_PATH=$RCMF90/lib:$LD_LIBRARY_PATH

export MAKEDEPF90=$INSTALL_DIR/makedepf90
export PATH=$MAKEDEPF90/bin:$PATH

export CALIPER=$INSTALL_DIR/caliper-$CMP-v$CALIPER_VERSION
export LD_LIBRARY_PATH=$CALIPER/lib64:$LD_LIBRARY_PATH

export LIKWID=$INSTALL_DIR/likwid-$CMP-v$LIKWID_VERSION
export LD_LIBRARY_PATH=$LIKWID/lib:$LD_LIBRARY_PATH
