# macOS with GNU compilers configuration
cc: mpicc
cxx: mpicxx
fc: mpifort

install_dir: ~/Development/ccs-libs

# Override dependency-specific settings if needed
dependencies:
  petsc:
    configure_options:
      - "--download-fblaslapack=yes"
      - "--with-fortran-datatypes=1"
      - "--with-fortran-interfaces=1"
      - "--with-fortran-bindings=1"
      - "--with-fortran-kernels=1"
      - "--with-debugging=1"